platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

environment:
  matrix:
    - language: cpp

clone_folder: c:\projects\shaka-packager\src

install:
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ..\depot_tools\

before_build:
  - cd ..
  - depot_tools\gclient config https://github.com/google/shaka-packager.git --name=src --unmanaged
  - set GYP_DEFINES='target_arch="%PLATFORM%"'
  - depot_tools\gclient sync

build_script:
  - cd src
  - if [%PLATFORM%] == [x64] (
      set output_dir=%CONFIGURATION%_%PLATFORM%
    ) else (
      set output_dir=%CONFIGURATION%
    )
  - copy "out\%OUTPUT_DIR%\packager.exe" packager-win.exe

test_script:
  - for %%f in ("out\%OUTPUT_DIR%\*_*test.exe") do (%%f || exit /b 666)
  - python "out\%OUTPUT_DIR%\packager_test.py" -v

artifacts:
  - path: packager-win.exe

deploy:
  provider: GitHub
  auth_token:
    secure: 0XTjRSDCHGH24WSnQRRizvhnaxK8gbq1cfivyuKQRrfwGPm7wpgiPL9SlyQ0aNdY
  on:
    appveyor_repo_tag: true
    platform: x64
    configuration: Release

branches:
  only:
    - master
    - "/^v\\d+\\./"
